---
require:
- rubocop-rspec
- rubocop-rails
AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/ImplicitExpect:
  EnforcedStyle: should
Rails/I18nLocaleTexts:
  Enabled: false
